### PR TITLE
Feat/small visual and functional fixes part 7

### LINKED ISSUE #733: Control Block-Spacing

### LINKED ISSUE #851: Navigation: Animation beim hochscrollen (Desktop)
Die Hauptnavigation auf Desktop bewegt sich beim Wechsel von der weissen Navigation (Scroll) zur dunklen Navigation (Top) von oben nach unten herein.

Soll: Fade-out Animation der weissen Navigation ohne hineinbewegen der darunterliegenden Hauptnavigation.

Image

### LINKED ISSUE #875: ⚠️ Subnavigation: Early Career Award (Desktop)
⚠️  Kritisch

Ist: Die Subnavigation hat eine fixe Höhe. Der Early Career Award ist dadurch nicht sichtbar.

Image

Soll: Die Höhe soll dynamisch und alle Navigation sichtbar sein. 

Spacing innerhalb der Subnavigation:
* Top: 24 Desktop / 48 Large
* Bottom: 48 Desktop / 96 Large

### LINKED ISSUE #876: Section: Spacing bottom
Ist: Auf den Detailseiten ist der Abstand beim Inhaltsbereich (weisser Hintergrund) gegen unten zur nächsten Section zu klein.

Image

Soll: Der Abstand soll doppelt so gross sein (bottom padding: section-bottom).

Image

### LINKED ISSUE #887: Publikationen Übersicht: Bottom Spacing
Ist: Der Abstand auf der Publikationsübersicht unterhalb der Section zum Footer ist zu gross.

Image

Soll: section-bottom als spacing verwenden.

Image

### LINKED ISSUE #888: Veranstaltungs-Teaser
Ist: 
* Vertikaler Abstand zwischen Titel und Subtext ist zu gross (dynamisch, je nach Breakpoint)
* Kein vertikaler Abstand zwischen Tag und Monat/Jahr
* Text-Format für Tag (Nummer) nicht korrekt

Image

Soll:
* Vertikaler Abstand zwischen Titel und Subtext: 16px
* Vertikaler Abstand zwischen Tag und Monat/Jahr: 12px
* Text-Format für Tag (Nummer):
color: var(--icon-primary, #1E3241);
text-align: center;
leading-trim: both;

text-edge: cap;
font-variant-numeric: lining-nums tabular-nums;
font-feature-settings: 'ss02' on, 'ss06' on;
font-family: var(--title-heading-3-font-family, "Helvetica Now Display");
font-size: 48px; (Desktop/Large)
font-size: 40px; (Mobile/Tablet)
font-style: normal;
font-weight: 700;
line-height: 120%; 

Image

### LINKED ISSUE #924: Wrong Network svg on Home
We accidentally added the wrong "network" icon on the home teaser. We used the "404" icon. See screenshot for correct icon:

Image

Please switch 404 and network icons.

### LINKED ISSUE #961: Link behind logo FG
This issue affects the header on FG website. If I click onto the logo in the header, I get directed to SAGW home. I should be directed to the home of the respective FG website.

### LINKED ISSUE #962: Footer FG: Link behind member of logo
If I click on the SAGW logo (member of) in the FG footer, I get directed to a vercel error page. I should be directed to sagw home.

### LINKED ISSUE #976: Header covers keyvisual lines on mobile

### LINKED ISSUE #983: Wrong color: Form title and subtitle
Image

### PR DESCRIPTION
**Pull request by mbleuer**
Closes #733
Closes #851
Closes #875
Closes #876
Closes #887
Closes #888
Closes #924
Closes #961
Closes #962
Closes #976
Closes #983

### CODE REVIEW

File: src/app/(frontend)/renderers/RenderFooter.tsx [hunk 1]
```diff
@@ -147,7 +147,7 @@ export const RenderFooter = async ({
     contact: footerContactData,
     dataPrivacyPageId: footerDataPrivacyPage.docs[0].id,
     fg,
-    homeLink: `/${locale}`,
+    homeLink: `${process.env.NEXT_PUBLIC_SERVER_URL}/${locale}`,
```
Comment (feerglas) [inline src/app/(frontend)/renderers/RenderFooter.tsx]: you should use

```getServerSideURL()```

here

File: src/app/(frontend)/renderers/RenderHeader.tsx [hunk 2]
```diff
@@ -61,10 +61,17 @@ export const RenderHeader = async ({
     return <CMSConfigError message='No metanav data in header data' />;
   }
 
+  // logo link
+  let logoLink = `${process.env.NEXT_PUBLIC_SERVER_URL}/${locale}`;
```
Comment (feerglas) [inline src/app/(frontend)/renderers/RenderHeader.tsx]: same here:

```getServerSideURL()```
